const authTypes = {
  SIGN_USER_UP_START: "SIGN_USER_UP_START",
  SIGN_USER_UP_SUCCESS: "SIGN_USER_UP_SUCCESS",
  SIGN_USER_UP_FAILURE: "SIGN_USER_UP_FAILURE",
  LOG_USER_IN_START: "LOG_USER_IN_START",
  LOG_USER_IN_SUCCESS: "LOG_USER_IN_SUCCESS",
  LOG_USER_IN_FAILURE: "LOG_USER_IN_FAILURE",
  LOG_USER_OUT_START: "LOG_USER_OUT_START",
  LOG_USER_OUT_SUCCESS: "LOG_USER_OUT_SUCCESS",
  LOG_USER_OUT_FAILURE: "LOG_USER_OUT_FAILURE",
  FETCH_AUTH_OBJECT_START: "FETCH_AUTH_OBJECT_START",
  FETCH_AUTH_OBJECT_SUCCESS: "FETCH_AUTH_OBJECT_SUCCESS",
  FETCH_AUTH_OBJECT_FAILURE: "FETCH_AUTH_OBJECT_FAILURE",
};

export default authTypes;
